### PR TITLE
Add proxy-charm support for RDS MySQL

### PR DESCRIPTION
**Pull request by johnsca**
Adds support for the integrator to serve as a proxy charm for the mysql interface backed by Amazon's RDS.
    
Resolves https://bugs.launchpad.net/charm-aws-integrator/+bug/1883963

### CODE REVIEW

**Comment by johnsca** [comment]
Tested with in-model relation, as well as CMR to both an machine model and k8s model (using `cs:~juju/mediawiki-k8s`) from AWS and Azure.

**Comment by johnsca** [comment]
Example for testing this:

```
juju switch aws:default
juju deploy --trust cs:~johnsca/aws-integrator-rds-mysql --channel=edge aws-integrator
juju offer aws-integrator.rds-mysql mysql
juju switch azure:k8s-model
juju deploy cs:~juju/mediawiki-k8s
juju consume aws:default.mysql
juju add-relation mediawiki-k8s:db mysql
```

**Comment by johnsca** [comment]
Docs PR: https://github.com/charmed-kubernetes/kubernetes-docs/pull/420

**Review by tvansteenburgh — APPROVED** [review]
Thanks @johnsca

**Comment by evilnick** [comment]
I got a bit confused by having to change the readme, but then I realised I changed the readme in the other repo https://github.com/charmed-kubernetes/charm-aws-integrator/

**Pull request merged**
